#ifndef MULTIBOOT2_H_
#define MULTIBOOT2_H_

#define MULTIBOOT2_HEADER_MAGIC			0xe85250d6
#define MULTIBOOT_ARCHITECTURE_i386		0

#define MULTIBOOT_HEADER_TAG_MODULE_ALIGN	6

#define MULTIBOOT_HEADER_TAG_END			0

#endif // MULTIBOOT2_H_
