DEPTH = ../../../
include ../../com_mak.txt

SYS	= kernel.sys
SYS_OBJS= main.obj
LDSCRIPT= kernel.ld

default	:
	make $(SYS)

$(SYS)	: $(SYS_OBJS)
	@echo "neko!w"

build:
	@echo "neko!w"
	make

clean:
	rm -f $(SYS)
